### ISSUE TITLE
Saving partially(?) broken in v45

### ISSUE THREAD

**Issue by dopadream** [x753/Lethal-Company-More-Suits#20] opened 2023-12-13 22:46 UTC
Hi, since v45 of Lethal Company released, any custom suits that are added to the terminal with the PRICE tag automatically unlock themselves when you reload your save.

In other words, this mod no longer properly saves what suits you have/haven't bought. It just assumes you bought them all and unlocks them all after loading a previously played save file.

**Comment by dopadream** [comment] 2023-12-13 22:48
I found out someone with my exact issue already made a report here: https://github.com/x753/Lethal-Company-More-Suits/issues/17
but it was closed prematurely with the assumption that making a new save file fixes it; it does NOT fix it, I suggest you close this issue and re-open that one

**Comment by x753** [comment] 2023-12-13 23:26
The issue is now fixed as of v1.4.0

**Closed by x753** 2023-12-13 23:26 UTC

**Comment by dopadream** [comment] 2023-12-13 23:39
goated
